# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_TaskManager(object):
    def setupUi(self, TaskManager):
        TaskManager.setObjectName("TaskManager")
        TaskManager.resize(1069, 790)
        self.to_do_label = QtWidgets.QLabel(parent=TaskManager)
        self.to_do_label.setGeometry(QtCore.QRect(10, 10, 351, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.to_do_label.setFont(font)
        self.to_do_label.setStyleSheet("   QLabel {\n"
"       background-color: rgb(205, 161, 255);\n"
"       border: 2px solid black;\n"
"       color: black;\n"
"   }\n"
"  \n"
"")
        self.to_do_label.setObjectName("to_do_label")
        self.doing_label = QtWidgets.QLabel(parent=TaskManager)
        self.doing_label.setGeometry(QtCore.QRect(360, 10, 351, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.doing_label.setFont(font)
        self.doing_label.setStyleSheet("   QLabel {\n"
"       background-color: rgb(119, 180, 255);\n"
"       border: 2px solid black;\n"
"       color: black;\n"
"   }\n"
"  ")
        self.doing_label.setObjectName("doing_label")
        self.done_label = QtWidgets.QLabel(parent=TaskManager)
        self.done_label.setGeometry(QtCore.QRect(710, 10, 351, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.done_label.setFont(font)
        self.done_label.setStyleSheet("   QLabel {\n"
"    background-color: rgb(74, 244, 36);\n"
"border: 2px solid black;\n"
"       color: black;\n"
"   }\n"
" ")
        self.done_label.setObjectName("done_label")
        self.to_do_list = QtWidgets.QListWidget(parent=TaskManager)
        self.to_do_list.setGeometry(QtCore.QRect(10, 70, 351, 711))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.to_do_list.setFont(font)
        self.to_do_list.setStyleSheet("   QListWidget {\n"
"       border: 2px solid black;\n"
"       background-color: rgb(230, 230, 230);\n"
"   }\n"
"   \n"
"")
        self.to_do_list.setObjectName("to_do_list")
        self.doing_list = QtWidgets.QListWidget(parent=TaskManager)
        self.doing_list.setGeometry(QtCore.QRect(360, 70, 351, 711))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.doing_list.setFont(font)
        self.doing_list.setStyleSheet("   QListWidget {\n"
"       border: 2px solid black;\n"
"       background-color: rgb(230, 230, 230);\n"
"   }\n"
"   \n"
"")
        self.doing_list.setObjectName("doing_list")
        self.done_list = QtWidgets.QListWidget(parent=TaskManager)
        self.done_list.setGeometry(QtCore.QRect(710, 70, 351, 711))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.done_list.setFont(font)
        self.done_list.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.NoContextMenu)
        self.done_list.setStyleSheet("   QListWidget {\n"
"       border: 2px solid black;\n"
"       background-color: rgb(230, 230, 230);\n"
"   }\n"
"   \n"
"")
        self.done_list.setObjectName("done_list")
        self.add_to_do_ex_btn = QtWidgets.QPushButton(parent=TaskManager)
        self.add_to_do_ex_btn.setGeometry(QtCore.QRect(160, 710, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.add_to_do_ex_btn.setFont(font)
        self.add_to_do_ex_btn.setStyleSheet("   QPushButton {\n"
"       border-radius: 25px;\n"
"       background-color: rgb(37, 208, 255);\n"
"       border: 1,5px solid black;\n"
"   }\n"
"\n"
"   \n"
"")
        self.add_to_do_ex_btn.setObjectName("add_to_do_ex_btn")
        self.add_doing_ex_btn = QtWidgets.QPushButton(parent=TaskManager)
        self.add_doing_ex_btn.setGeometry(QtCore.QRect(510, 710, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.add_doing_ex_btn.setFont(font)
        self.add_doing_ex_btn.setStyleSheet("   QPushButton {\n"
"       border-radius: 25px;\n"
"       background-color: rgb(37, 208, 255);\n"
"       border: 1,5px solid black;\n"
"   }\n"
"\n"
"   \n"
"")
        self.add_doing_ex_btn.setObjectName("add_doing_ex_btn")
        self.add_done_ex_btn = QtWidgets.QPushButton(parent=TaskManager)
        self.add_done_ex_btn.setGeometry(QtCore.QRect(860, 710, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.add_done_ex_btn.setFont(font)
        self.add_done_ex_btn.setStyleSheet("   QPushButton {\n"
"       border-radius: 25px;\n"
"       background-color: rgb(37, 208, 255);\n"
"       border: 1,5px solid black;\n"
"   }\n"
"\n"
"   \n"
"")
        self.add_done_ex_btn.setObjectName("add_done_ex_btn")
        self.sort_to_do_btn = QtWidgets.QPushButton(parent=TaskManager)
        self.sort_to_do_btn.setGeometry(QtCore.QRect(300, 20, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.sort_to_do_btn.setFont(font)
        self.sort_to_do_btn.setStyleSheet("QPushButton {\n"
"    background-color: rgb(205, 161, 255);\n"
"    border: 0.1 px;\n"
"}")
        self.sort_to_do_btn.setObjectName("sort_to_do_btn")
        self.sort_doing_btn = QtWidgets.QPushButton(parent=TaskManager)
        self.sort_doing_btn.setGeometry(QtCore.QRect(650, 20, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.sort_doing_btn.setFont(font)
        self.sort_doing_btn.setStyleSheet("QPushButton {\n"
"    background-color: rgb(119, 180, 255);\n"
"    border: 0.1 px;\n"
"}")
        self.sort_doing_btn.setObjectName("sort_doing_btn")
        self.sort_done_btn = QtWidgets.QPushButton(parent=TaskManager)
        self.sort_done_btn.setGeometry(QtCore.QRect(1000, 20, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.sort_done_btn.setFont(font)
        self.sort_done_btn.setStyleSheet("QPushButton {\n"
"    background-color: rgb(74, 244, 36);\n"
"    border: 0.1 px;\n"
"}")
        self.sort_done_btn.setObjectName("sort_done_btn")

        self.retranslateUi(TaskManager)
        QtCore.QMetaObject.connectSlotsByName(TaskManager)

    def retranslateUi(self, TaskManager):
        _translate = QtCore.QCoreApplication.translate
        TaskManager.setWindowTitle(_translate("TaskManager", "Менеджер задач"))
        self.to_do_label.setText(_translate("TaskManager", "To Do"))
        self.doing_label.setText(_translate("TaskManager", "Doing"))
        self.done_label.setText(_translate("TaskManager", "Done"))
        self.add_to_do_ex_btn.setText(_translate("TaskManager", "+"))
        self.add_doing_ex_btn.setText(_translate("TaskManager", "+"))
        self.add_done_ex_btn.setText(_translate("TaskManager", "+"))
        self.sort_to_do_btn.setText(_translate("TaskManager", "• —\n"
"• —"))
        self.sort_doing_btn.setText(_translate("TaskManager", "• —\n"
"• —"))
        self.sort_done_btn.setText(_translate("TaskManager", "• —\n"
"• —"))
