# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1069, 838)
        self.to_do_label = QtWidgets.QLabel(parent=Form)
        self.to_do_label.setGeometry(QtCore.QRect(10, 10, 351, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.to_do_label.setFont(font)
        self.to_do_label.setStyleSheet("   QLabel {\n"
                                       "       background-color: rgb(205, 161, 255);\n"
                                       "       border: 2px solid black;\n"
                                       "       color: black;\n"
                                       "   }\n"
                                       "  \n"
                                       "")
        self.to_do_label.setObjectName("to_do_label")
        self.doing_label = QtWidgets.QLabel(parent=Form)
        self.doing_label.setGeometry(QtCore.QRect(360, 10, 351, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.doing_label.setFont(font)
        self.doing_label.setStyleSheet("   QLabel {\n"
                                       "       background-color: rgb(119, 180, 255);\n"
                                       "       border: 2px solid black;\n"
                                       "       color: black;\n"
                                       "   }\n"
                                       "  ")
        self.doing_label.setObjectName("doing_label")
        self.done_label = QtWidgets.QLabel(parent=Form)
        self.done_label.setGeometry(QtCore.QRect(710, 10, 351, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.done_label.setFont(font)
        self.done_label.setStyleSheet("   QLabel {\n"
                                      "    background-color: rgb(74, 244, 36);\n"
                                      "border: 2px solid black;\n"
                                      "       color: black;\n"
                                      "   }\n"
                                      " ")
        self.done_label.setObjectName("done_label")
        self.to_do_list = QtWidgets.QListWidget(parent=Form)
        self.to_do_list.setGeometry(QtCore.QRect(10, 70, 351, 761))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.to_do_list.setFont(font)
        self.to_do_list.setStyleSheet("   QListWidget {\n"
                                      "       border: 2px solid black;\n"
                                      "   }\n"
                                      "   \n"
                                      "")
        self.to_do_list.setObjectName("to_do_list")
        self.doing_list = QtWidgets.QListWidget(parent=Form)
        self.doing_list.setGeometry(QtCore.QRect(360, 70, 351, 761))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.doing_list.setFont(font)
        self.doing_list.setStyleSheet("   QListWidget {\n"
                                      "       border: 2px solid black;\n"
                                      "   }\n"
                                      "   \n"
                                      "")
        self.doing_list.setObjectName("doing_list")
        self.done_list = QtWidgets.QListWidget(parent=Form)
        self.done_list.setGeometry(QtCore.QRect(710, 70, 351, 761))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.done_list.setFont(font)
        self.done_list.setStyleSheet("   QListWidget {\n"
                                     "       border: 2px solid black;\n"
                                     "   }\n"
                                     "   \n"
                                     "")
        self.done_list.setObjectName("done_list")
        self.add_to_do_btn = QtWidgets.QPushButton(parent=Form)
        self.add_to_do_btn.setGeometry(QtCore.QRect(150, 750, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.add_to_do_btn.setFont(font)
        self.add_to_do_btn.setStyleSheet("   QPushButton {\n"
                                         "       border-radius: 25px;\n"
                                         "       background-color: rgb(37, 208, 255);\n"
                                         "       border: 1,5px solid black;\n"
                                         "   }\n"
                                         "\n"
                                         "   \n"
                                         "")
        self.add_to_do_btn.setObjectName("add_to_do_btn")
        self.add_doing_btn = QtWidgets.QPushButton(parent=Form)
        self.add_doing_btn.setGeometry(QtCore.QRect(500, 750, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.add_doing_btn.setFont(font)
        self.add_doing_btn.setStyleSheet("   QPushButton {\n"
                                         "       border-radius: 25px;\n"
                                         "       background-color: rgb(37, 208, 255);\n"
                                         "       border: 1,5px solid black;\n"
                                         "   }\n"
                                         "\n"
                                         "   \n"
                                         "")
        self.add_doing_btn.setObjectName("add_doing_btn")
        self.add_done_btn = QtWidgets.QPushButton(parent=Form)
        self.add_done_btn.setGeometry(QtCore.QRect(860, 750, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.add_done_btn.setFont(font)
        self.add_done_btn.setStyleSheet("   QPushButton {\n"
                                        "       border-radius: 25px;\n"
                                        "       background-color: rgb(37, 208, 255);\n"
                                        "       border: 1,5px solid black;\n"
                                        "   }\n"
                                        "\n"
                                        "   \n"
                                        "")
        self.add_done_btn.setObjectName("add_done_btn")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.to_do_label.setText(_translate("Form", "To Do"))
        self.doing_label.setText(_translate("Form", "Doing"))
        self.done_label.setText(_translate("Form", "Done"))
        self.add_to_do_btn.setText(_translate("Form", "+"))
        self.add_doing_btn.setText(_translate("Form", "+"))
        self.add_done_btn.setText(_translate("Form", "+"))
